server:
  port: 8088

xxl:
  job:
    executor:
      address:  # 执行器注册（选填）
      appname: xxl-job-executor-sample # 执行器appName
      ip: 127.0.0.1
      port: 9999
    accessToken: default_token # 执行器通讯token
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin  # 调度中心部署地址
  login:
    username: admin
    password: 123456
    ifRemember: on



      
      
      
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xxl_job_demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1234
